[package]
name = "deepslate-converter"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"]}
rayon = "1"
deepslate = {path = "../"}
anyhow.workspace = true
simdnbt = "0.6.1"
fastanvil = "0.31"