name: CI

on:
  pull_request:
  merge_group:
  push: # Run CI on the main branch after every merge. This is important to fill the GitHub Actions cache in a way that pull requests can see it
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:

  deepslate-tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.9.0

      - name: Run tests
        run: cargo test --workspace --all-features --all-targets